<?php
session_start(); include "config/koneksi.php";
$kategori_id=isset($_GET['kategori'])?(int)$_GET['kategori']:0; $keyword=trim($_GET['keyword']??'');
$kategori=mysqli_query($conn,"SELECT * FROM kategori ORDER BY nama_kategori ASC");
$where=[]; if($kategori_id>0)$where[]="buku.id_kategori=$kategori_id"; if($keyword!==''){ $safe=mysqli_real_escape_string($conn,$keyword); $where[]="(buku.judul_buku LIKE '%$safe%' OR buku.penulis LIKE '%$safe%')"; }
$sql="SELECT buku.*, kategori.nama_kategori FROM buku INNER JOIN kategori ON buku.id_kategori=kategori.id_kategori".($where?' WHERE '.implode(' AND ',$where):'')." ORDER BY buku.id_buku DESC"; $data=mysqli_query($conn,$sql);
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Koleksi | LENTERA</title><link rel="icon" type="image/svg+xml" href="images/favicon.svg">
<link rel="stylesheet" href="css/style.css"></head><body>
<nav class="navbar"><a class="logo" href="index.php"><span class="logo-mark">L</span><span>LENTERA<small>BOOKS & STORIES</small></span></a><button class="nav-toggle" type="button" aria-label="Buka menu" aria-expanded="false">☰</button><ul class="nav-menu"><li><a href="index.php">Beranda</a></li><li><a class="active" href="katalog.php">Koleksi</a></li><?php if(isset($_SESSION['role'])){ ?><li><a href="<?= $_SESSION['role']=='admin'?'admin/index.php':'user/index.php' ?>">Dashboard</a></li><li><a href="logout.php">Keluar</a></li><?php }else{ ?><li><a href="login.php">Masuk</a></li><li><a class="nav-cta" href="register.php">Daftar</a></li><?php } ?></ul></nav>
<header class="page-masthead"><span class="section-kicker">PERPUSTAKAAN KAMI</span><h1>Koleksi Buku</h1><p>Telusuri rak, pilih kategori, atau cari judul yang ingin kamu bawa pulang.</p></header>
<div class="content-user catalog-page"><form class="catalog-toolbar" method="get"><div class="search-field"><input name="keyword" value="<?= htmlspecialchars($keyword) ?>" placeholder="Cari judul atau penulis..."><button>⌕</button></div><select name="kategori" onchange="this.form.submit()"><option value="0">Semua Kategori</option><?php while($k=mysqli_fetch_assoc($kategori)){ ?><option value="<?= $k['id_kategori'] ?>" <?= $kategori_id==(int)$k['id_kategori']?'selected':'' ?>><?= htmlspecialchars($k['nama_kategori']) ?></option><?php } ?></select><button class="btn filter-btn">Terapkan</button><?php if($kategori_id||$keyword!==''){ ?><a class="clear-filter" href="katalog.php">Reset</a><?php } ?></form>
<div class="result-note"><?= mysqli_num_rows($data) ?> buku ditemukan</div><div class="book-container"><?php if(mysqli_num_rows($data)){ while($row=mysqli_fetch_assoc($data)){ ?><article class="book-card"><div class="cover-wrap"><img src="images/buku/<?= htmlspecialchars($row['gambar']) ?>" alt="<?= htmlspecialchars($row['judul_buku']) ?>"></div><div class="book-meta"><span class="book-category"><?= htmlspecialchars($row['nama_kategori']) ?></span><h3><?= htmlspecialchars($row['judul_buku']) ?></h3><p class="author"><?= htmlspecialchars($row['penulis']) ?></p><div class="book-bottom"><strong>Rp <?= number_format($row['harga'],0,',','.') ?></strong><a class="mini-link" href="<?= isset($_SESSION['role'])&&$_SESSION['role']=='user'?'user/detail_buku.php?id='.$row['id_buku']:'login.php' ?>">Detail →</a></div></div></article><?php }}else{ ?><div class="empty-cart"><h3>Tidak ada buku di rak ini</h3><p>Coba kategori lain atau hapus kata pencarian.</p></div><?php } ?></div></div>
<footer><div><b>LENTERA</b><p>Menerangi Setiap Halaman.</p></div><p>© 2026 LENTERA</p></footer><script src="js/ui.js"></script>
</body></html>